const pokemons = {
  'Bulbasaur': 'bulbasaur',
  'Ivysaur': 'ivysaur',
  'Venusaur': 'venusaur',
  'Mega Venusaur': 'venusaur-mega',
  'Charmander': 'charmander',
  'Charmeleon': 'charmeleon',
  'Charizard': 'charizard',
  'Mega Charizard X': 'charizard-mega-x',
  'Mega Charizard Y': 'charizard-mega-y',
  'Squirtle': 'squirtle',
  'Wartortle': 'wartortle',
  'Blastoise': 'blastoise',
  'Mega Blastoise': 'blastoise-mega',
  'Caterpie': 'caterpie',
  'Metapod': 'metapod',
  'Butterfree': 'butterfree',
  'Weedle': 'weedle',
  'Kakuna': 'kakuna',
  'Beedrill': 'beedrill',
  'Mega Beedrill': 'beedrill-mega',
  'Pidgey': 'pidgey',
  'Pidgeotto': 'pidgeotto',
  'Pidgeot': 'pidgeot',
  'Mega Pidgeot': 'pidgeot-mega',
  'Rattata': 'rattata',
  'Alolan Rattata': 'rattata-alolan',
  'Raticate': 'raticate',
  'Alolan Raticate': 'raticate-alolan',
  'Spearow': 'spearow',
  'Fearow': 'fearow',
  'Ekans': 'ekans',
  'Arbok': 'arbok',
  'Pikachu': 'pikachu',
  'Pikachu (Partner Pikachu)': 'pikachu-lets-go',
  'Raichu': 'raichu',
  'Alolan Raichu': 'raichu-alolan',
  'Sandshrew': 'sandshrew',
  'Alolan Sandshrew': 'sandshrew-alolan',
  'Sandslash': 'sandslash',
  'Alolan Sandslash': 'sandslash-alolan',
  'Nidoran♀': 'nidoran-f',
  'Nidorina': 'nidorina',
  'Nidoqueen': 'nidoqueen',
  'Nidoran♂': 'nidoran-m',
  'Nidorino': 'nidorino',
  'Nidoking': 'nidoking',
  'Clefairy': 'clefairy',
  'Clefable': 'clefable',
  'Vulpix': 'vulpix',
  'Alolan Vulpix': 'vulpix-alolan',
  'Ninetales': 'ninetales',
  'Alolan Ninetales': 'ninetales-alolan',
  'Jigglypuff': 'jigglypuff',
  'Wigglytuff': 'wigglytuff',
  'Zubat': 'zubat',
  'Golbat': 'golbat',
  'Oddish': 'oddish',
  'Gloom': 'gloom',
  'Vileplume': 'vileplume',
  'Paras': 'paras',
  'Parasect': 'parasect',
  'Venonat': 'venonat',
  'Venomoth': 'venomoth',
  'Diglett': 'diglett',
  'Alolan Diglett': 'diglett-alolan',
  'Dugtrio': 'dugtrio',
  'Alolan Dugtrio': 'dugtrio-alolan',
  'Meowth': 'meowth',
  'Alolan Meowth': 'meowth-alolan',
  'Persian': 'persian',
  'Alolan Persian': 'persian-alolan',
  'Psyduck': 'psyduck',
  'Golduck': 'golduck',
  'Mankey': 'mankey',
  'Primeape': 'primeape',
  'Growlithe': 'growlithe',
  'Arcanine': 'arcanine',
  'Poliwag': 'poliwag',
  'Poliwhirl': 'poliwhirl',
  'Poliwrath': 'poliwrath',
  'Abra': 'abra',
  'Kadabra': 'kadabra',
  'Alakazam': 'alakazam',
  'Mega Alakazam': 'alakazam-mega',
  'Machop': 'machop',
  'Machoke': 'machoke',
  'Machamp': 'machamp',
  'Bellsprout': 'bellsprout',
  'Weepinbell': 'weepinbell',
  'Victreebel': 'victreebel',
  'Tentacool': 'tentacool',
  'Tentacruel': 'tentacruel',
  'Geodude': 'geodude',
  'Alolan Geodude': 'geodude-alolan',
  'Graveler': 'graveler',
  'Alolan Graveler': 'graveler-alolan',
  'Golem': 'golem',
  'Alolan Golem': 'golem-alolan',
  'Ponyta': 'ponyta',
  'Rapidash': 'rapidash',
  'Slowpoke': 'slowpoke',
  'Slowbro': 'slowbro',
  'Mega Slowbro': 'slowbro-mega',
  'Magnemite': 'magnemite',
  'Magneton': 'magneton',
  'Farfetch\'d': 'farfetchd',
  'Doduo': 'doduo',
  'Dodrio': 'dodrio',
  'Seel': 'seel',
  'Dewgong': 'dewgong',
  'Grimer': 'grimer',
  'Alolan Grimer': 'grimer-alolan',
  'Muk': 'muk',
  'Alolan Muk': 'muk-alolan',
  'Shellder': 'shellder',
  'Cloyster': 'cloyster',
  'Gastly': 'gastly',
  'Haunter': 'haunter',
  'Gengar': 'gengar',
  'Mega Gengar': 'gengar-mega',
  'Onix': 'onix',
  'Drowzee': 'drowzee',
  'Hypno': 'hypno',
  'Krabby': 'krabby',
  'Kingler': 'kingler',
  'Voltorb': 'voltorb',
  'Electrode': 'electrode',
  'Exeggcute': 'exeggcute',
  'Exeggutor': 'exeggutor',
  'Alolan Exeggutor': 'exeggutor-alolan',
  'Cubone': 'cubone',
  'Marowak': 'marowak',
  'Alolan Marowak': 'marowak-alolan',
  'Hitmonlee': 'hitmonlee',
  'Hitmonchan': 'hitmonchan',
  'Lickitung': 'lickitung',
  'Koffing': 'koffing',
  'Weezing': 'weezing',
  'Rhyhorn': 'rhyhorn',
  'Rhydon': 'rhydon',
  'Chansey': 'chansey',
  'Tangela': 'tangela',
  'Kangaskhan': 'kangaskhan',
  'Mega Kangaskhan': 'kangaskhan-mega',
  'Horsea': 'horsea',
  'Seadra': 'seadra',
  'Goldeen': 'goldeen',
  'Seaking': 'seaking',
  'Staryu': 'staryu',
  'Starmie': 'starmie',
  'Mr. Mime': 'mr-mime',
  'Scyther': 'scyther',
  'Jynx': 'jynx',
  'Electabuzz': 'electabuzz',
  'Magmar': 'magmar',
  'Pinsir': 'pinsir',
  'Mega Pinsir': 'pinsir-mega',
  'Tauros': 'tauros',
  'Magikarp': 'magikarp',
  'Gyarados': 'gyarados',
  'Mega Gyarados': 'gyarados-mega',
  'Lapras': 'lapras',
  'Ditto': 'ditto',
  'Eevee': 'eevee',
  'Eevee (Partner Eevee)': 'eevee-lets-go',
  'Vaporeon': 'vaporeon',
  'Jolteon': 'jolteon',
  'Flareon': 'flareon',
  'Porygon': 'porygon',
  'Omanyte': 'omanyte',
  'Omastar': 'omastar',
  'Kabuto': 'kabuto',
  'Kabutops': 'kabutops',
  'Aerodactyl': 'aerodactyl',
  'Mega Aerodactyl': 'aerodactyl-mega',
  'Snorlax': 'snorlax',
  'Articuno': 'articuno',
  'Zapdos': 'zapdos',
  'Moltres': 'moltres',
  'Dratini': 'dratini',
  'Dragonair': 'dragonair',
  'Dragonite': 'dragonite',
  'Mewtwo': 'mewtwo',
  'Mega Mewtwo X': 'mewtwo-mega-x',
  'Mega Mewtwo Y': 'mewtwo-mega-y',
  'Mew': 'mew',
  'Chikorita': 'chikorita',
  'Bayleef': 'bayleef',
  'Meganium': 'meganium',
  'Cyndaquil': 'cyndaquil',
  'Quilava': 'quilava',
  'Typhlosion': 'typhlosion',
  'Totodile': 'totodile',
  'Croconaw': 'croconaw',
  'Feraligatr': 'feraligatr',
  'Sentret': 'sentret',
  'Furret': 'furret',
  'Hoothoot': 'hoothoot',
  'Noctowl': 'noctowl',
  'Ledyba': 'ledyba',
  'Ledian': 'ledian',
  'Spinarak': 'spinarak',
  'Ariados': 'ariados',
  'Crobat': 'crobat',
  'Chinchou': 'chinchou',
  'Lanturn': 'lanturn',
  'Pichu': 'pichu',
  'Cleffa': 'cleffa',
  'Igglybuff': 'igglybuff',
  'Togepi': 'togepi',
  'Togetic': 'togetic',
  'Natu': 'natu',
  'Xatu': 'xatu',
  'Mareep': 'mareep',
  'Flaaffy': 'flaaffy',
  'Ampharos': 'ampharos',
  'Mega Ampharos': 'ampharos-mega',
  'Bellossom': 'bellossom',
  'Marill': 'marill',
  'Azumarill': 'azumarill',
  'Sudowoodo': 'sudowoodo',
  'Politoed': 'politoed',
  'Hoppip': 'hoppip',
  'Skiploom': 'skiploom',
  'Jumpluff': 'jumpluff',
  'Aipom': 'aipom',
  'Sunkern': 'sunkern',
  'Sunflora': 'sunflora',
  'Yanma': 'yanma',
  'Wooper': 'wooper',
  'Quagsire': 'quagsire',
  'Espeon': 'espeon',
  'Umbreon': 'umbreon',
  'Murkrow': 'murkrow',
  'Slowking': 'slowking',
  'Misdreavus': 'misdreavus',
  'Unown': 'unown',
  'Wobbuffet': 'wobbuffet',
  'Girafarig': 'girafarig',
  'Pineco': 'pineco',
  'Forretress': 'forretress',
  'Dunsparce': 'dunsparce',
  'Gligar': 'gligar',
  'Steelix': 'steelix',
  'Mega Steelix': 'steelix-mega',
  'Snubbull': 'snubbull',
  'Granbull': 'granbull',
  'Qwilfish': 'qwilfish',
  'Scizor': 'scizor',
  'Mega Scizor': 'scizor-mega',
  'Shuckle': 'shuckle',
  'Heracross': 'heracross',
  'Mega Heracross': 'heracross-mega',
  'Sneasel': 'sneasel',
  'Teddiursa': 'teddiursa',
  'Ursaring': 'ursaring',
  'Slugma': 'slugma',
  'Magcargo': 'magcargo',
  'Swinub': 'swinub',
  'Piloswine': 'piloswine',
  'Corsola': 'corsola',
  'Remoraid': 'remoraid',
  'Octillery': 'octillery',
  'Delibird': 'delibird',
  'Mantine': 'mantine',
  'Skarmory': 'skarmory',
  'Houndour': 'houndour',
  'Houndoom': 'houndoom',
  'Mega Houndoom': 'houndoom-mega',
  'Kingdra': 'kingdra',
  'Phanpy': 'phanpy',
  'Donphan': 'donphan',
  'Porygon2': 'porygon2',
  'Stantler': 'stantler',
  'Smeargle': 'smeargle',
  'Tyrogue': 'tyrogue',
  'Hitmontop': 'hitmontop',
  'Smoochum': 'smoochum',
  'Elekid': 'elekid',
  'Magby': 'magby',
  'Miltank': 'miltank',
  'Blissey': 'blissey',
  'Raikou': 'raikou',
  'Entei': 'entei',
  'Suicune': 'suicune',
  'Larvitar': 'larvitar',
  'Pupitar': 'pupitar',
  'Tyranitar': 'tyranitar',
  'Mega Tyranitar': 'tyranitar-mega',
  'Lugia': 'lugia',
  'Ho-oh': 'ho-oh',
  'Celebi': 'celebi',
  'Treecko': 'treecko',
  'Grovyle': 'grovyle',
  'Sceptile': 'sceptile',
  'Mega Sceptile': 'sceptile-mega',
  'Torchic': 'torchic',
  'Combusken': 'combusken',
  'Blaziken': 'blaziken',
  'Mega Blaziken': 'blaziken-mega',
  'Mudkip': 'mudkip',
  'Marshtomp': 'marshtomp',
  'Swampert': 'swampert',
  'Mega Swampert': 'swampert-mega',
  'Poochyena': 'poochyena',
  'Mightyena': 'mightyena',
  'Zigzagoon': 'zigzagoon',
  'Linoone': 'linoone',
  'Wurmple': 'wurmple',
  'Silcoon': 'silcoon',
  'Beautifly': 'beautifly',
  'Cascoon': 'cascoon',
  'Dustox': 'dustox',
  'Lotad': 'lotad',
  'Lombre': 'lombre',
  'Ludicolo': 'ludicolo',
  'Seedot': 'seedot',
  'Nuzleaf': 'nuzleaf',
  'Shiftry': 'shiftry',
  'Taillow': 'taillow',
  'Swellow': 'swellow',
  'Wingull': 'wingull',
  'Pelipper': 'pelipper',
  'Ralts': 'ralts',
  'Kirlia': 'kirlia',
  'Gardevoir': 'gardevoir',
  'Mega Gardevoir': 'gardevoir-mega',
  'Surskit': 'surskit',
  'Masquerain': 'masquerain',
  'Shroomish': 'shroomish',
  'Breloom': 'breloom',
  'Slakoth': 'slakoth',
  'Vigoroth': 'vigoroth',
  'Slaking': 'slaking',
  'Nincada': 'nincada',
  'Ninjask': 'ninjask',
  'Shedinja': 'shedinja',
  'Whismur': 'whismur',
  'Loudred': 'loudred',
  'Exploud': 'exploud',
  'Makuhita': 'makuhita',
  'Hariyama': 'hariyama',
  'Azurill': 'azurill',
  'Nosepass': 'nosepass',
  'Skitty': 'skitty',
  'Delcatty': 'delcatty',
  'Sableye': 'sableye',
  'Mega Sableye': 'sableye-mega',
  'Mawile': 'mawile',
  'Mega Mawile': 'mawile-mega',
  'Aron': 'aron',
  'Lairon': 'lairon',
  'Aggron': 'aggron',
  'Mega Aggron': 'aggron-mega',
  'Meditite': 'meditite',
  'Medicham': 'medicham',
  'Mega Medicham': 'medicham-mega',
  'Electrike': 'electrike',
  'Manectric': 'manectric',
  'Mega Manectric': 'manectric-mega',
  'Plusle': 'plusle',
  'Minun': 'minun',
  'Volbeat': 'volbeat',
  'Illumise': 'illumise',
  'Roselia': 'roselia',
  'Gulpin': 'gulpin',
  'Swalot': 'swalot',
  'Carvanha': 'carvanha',
  'Sharpedo': 'sharpedo',
  'Mega Sharpedo': 'sharpedo-mega',
  'Wailmer': 'wailmer',
  'Wailord': 'wailord',
  'Numel': 'numel',
  'Camerupt': 'camerupt',
  'Mega Camerupt': 'camerupt-mega',
  'Torkoal': 'torkoal',
  'Spoink': 'spoink',
  'Grumpig': 'grumpig',
  'Spinda': 'spinda',
  'Trapinch': 'trapinch',
  'Vibrava': 'vibrava',
  'Flygon': 'flygon',
  'Cacnea': 'cacnea',
  'Cacturne': 'cacturne',
  'Swablu': 'swablu',
  'Altaria': 'altaria',
  'Mega Altaria': 'altaria-mega',
  'Zangoose': 'zangoose',
  'Seviper': 'seviper',
  'Lunatone': 'lunatone',
  'Solrock': 'solrock',
  'Barboach': 'barboach',
  'Whiscash': 'whiscash',
  'Corphish': 'corphish',
  'Crawdaunt': 'crawdaunt',
  'Baltoy': 'baltoy',
  'Claydol': 'claydol',
  'Lileep': 'lileep',
  'Cradily': 'cradily',
  'Anorith': 'anorith',
  'Armaldo': 'armaldo',
  'Feebas': 'feebas',
  'Milotic': 'milotic',
  'Castform': 'castform',
  'Kecleon': 'kecleon',
  'Shuppet': 'shuppet',
  'Banette': 'banette',
  'Mega Banette': 'banette-mega',
  'Duskull': 'duskull',
  'Dusclops': 'dusclops',
  'Tropius': 'tropius',
  'Chimecho': 'chimecho',
  'Absol': 'absol',
  'Mega Absol': 'absol-mega',
  'Wynaut': 'wynaut',
  'Snorunt': 'snorunt',
  'Glalie': 'glalie',
  'Mega Glalie': 'glalie-mega',
  'Spheal': 'spheal',
  'Sealeo': 'sealeo',
  'Walrein': 'walrein',
  'Clamperl': 'clamperl',
  'Huntail': 'huntail',
  'Gorebyss': 'gorebyss',
  'Relicanth': 'relicanth',
  'Luvdisc': 'luvdisc',
  'Bagon': 'bagon',
  'Shelgon': 'shelgon',
  'Salamence': 'salamence',
  'Mega Salamence': 'salamence-mega',
  'Beldum': 'beldum',
  'Metang': 'metang',
  'Metagross': 'metagross',
  'Mega Metagross': 'metagross-mega',
  'Regirock': 'regirock',
  'Regice': 'regice',
  'Registeel': 'registeel',
  'Latias': 'latias',
  'Mega Latias': 'latias-mega',
  'Latios': 'latios',
  'Mega Latios': 'latios-mega',
  'Kyogre': 'kyogre',
  'Primal Kyogre': 'kyogre-primal',
  'Groudon': 'groudon',
  'Primal Groudon': 'groudon-primal',
  'Rayquaza': 'rayquaza',
  'Mega Rayquaza': 'rayquaza-mega',
  'Jirachi': 'jirachi',
  'Deoxys (Normal Forme)': 'deoxys-normal',
  'Deoxys (Attack Forme)': 'deoxys-attack',
  'Deoxys (Defense Forme)': 'deoxys-defense',
  'Deoxys (Speed Forme)': 'deoxys-speed',
  'Turtwig': 'turtwig',
  'Grotle': 'grotle',
  'Torterra': 'torterra',
  'Chimchar': 'chimchar',
  'Monferno': 'monferno',
  'Infernape': 'infernape',
  'Piplup': 'piplup',
  'Prinplup': 'prinplup',
  'Empoleon': 'empoleon',
  'Starly': 'starly',
  'Staravia': 'staravia',
  'Staraptor': 'staraptor',
  'Bidoof': 'bidoof',
  'Bibarel': 'bibarel',
  'Kricketot': 'kricketot',
  'Kricketune': 'kricketune',
  'Shinx': 'shinx',
  'Luxio': 'luxio',
  'Luxray': 'luxray',
  'Budew': 'budew',
  'Roserade': 'roserade',
  'Cranidos': 'cranidos',
  'Rampardos': 'rampardos',
  'Shieldon': 'shieldon',
  'Bastiodon': 'bastiodon',
  'Burmy': 'burmy',
  'Wormadam (Plant Cloak)': 'wormadam-plant',
  'Wormadam (Sandy Cloak)': 'wormadam-sandy',
  'Wormadam (Trash Cloak)': 'wormadam-trash',
  'Mothim': 'mothim',
  'Combee': 'combee',
  'Vespiquen': 'vespiquen',
  'Pachirisu': 'pachirisu',
  'Buizel': 'buizel',
  'Floatzel': 'floatzel',
  'Cherubi': 'cherubi',
  'Cherrim': 'cherrim',
  'Shellos': 'shellos',
  'Gastrodon': 'gastrodon',
  'Ambipom': 'ambipom',
  'Drifloon': 'drifloon',
  'Drifblim': 'drifblim',
  'Buneary': 'buneary',
  'Lopunny': 'lopunny',
  'Mega Lopunny': 'lopunny-mega',
  'Mismagius': 'mismagius',
  'Honchkrow': 'honchkrow',
  'Glameow': 'glameow',
  'Purugly': 'purugly',
  'Chingling': 'chingling',
  'Stunky': 'stunky',
  'Skuntank': 'skuntank',
  'Bronzor': 'bronzor',
  'Bronzong': 'bronzong',
  'Bonsly': 'bonsly',
  'Mime Jr.': 'mime-jr',
  'Happiny': 'happiny',
  'Chatot': 'chatot',
  'Spiritomb': 'spiritomb',
  'Gible': 'gible',
  'Gabite': 'gabite',
  'Garchomp': 'garchomp',
  'Mega Garchomp': 'garchomp-mega',
  'Munchlax': 'munchlax',
  'Riolu': 'riolu',
  'Lucario': 'lucario',
  'Mega Lucario': 'lucario-mega',
  'Hippopotas': 'hippopotas',
  'Hippowdon': 'hippowdon',
  'Skorupi': 'skorupi',
  'Drapion': 'drapion',
  'Croagunk': 'croagunk',
  'Toxicroak': 'toxicroak',
  'Carnivine': 'carnivine',
  'Finneon': 'finneon',
  'Lumineon': 'lumineon',
  'Mantyke': 'mantyke',
  'Snover': 'snover',
  'Abomasnow': 'abomasnow',
  'Mega Abomasnow': 'abomasnow-mega',
  'Weavile': 'weavile',
  'Magnezone': 'magnezone',
  'Lickilicky': 'lickilicky',
  'Rhyperior': 'rhyperior',
  'Tangrowth': 'tangrowth',
  'Electivire': 'electivire',
  'Magmortar': 'magmortar',
  'Togekiss': 'togekiss',
  'Yanmega': 'yanmega',
  'Leafeon': 'leafeon',
  'Glaceon': 'glaceon',
  'Gliscor': 'gliscor',
  'Mamoswine': 'mamoswine',
  'Porygon-Z': 'porygon-z',
  'Gallade': 'gallade',
  'Mega Gallade': 'gallade-mega',
  'Probopass': 'probopass',
  'Dusknoir': 'dusknoir',
  'Froslass': 'froslass',
  'Rotom': 'rotom',
  'Rotom (Heat Rotom)': 'rotom-heat',
  'Rotom (Wash Rotom)': 'rotom-wash',
  'Rotom (Frost Rotom)': 'rotom-frost',
  'Rotom (Fan Rotom)': 'rotom-fan',
  'Rotom (Mow Rotom)': 'rotom-mow',
  'Uxie': 'uxie',
  'Mesprit': 'mesprit',
  'Azelf': 'azelf',
  'Dialga': 'dialga',
  'Palkia': 'palkia',
  'Heatran': 'heatran',
  'Regigigas': 'regigigas',
  'Giratina (Altered Forme)': 'giratina-altered',
  'Giratina (Origin Forme)': 'giratina-origin',
  'Cresselia': 'cresselia',
  'Phione': 'phione',
  'Manaphy': 'manaphy',
  'Darkrai': 'darkrai',
  'Shaymin (Land Forme)': 'shaymin-land',
  'Shaymin (Sky Forme)': 'shaymin-sky',
  'Arceus': 'arceus',
  'Victini': 'victini',
  'Snivy': 'snivy',
  'Servine': 'servine',
  'Serperior': 'serperior',
  'Tepig': 'tepig',
  'Pignite': 'pignite',
  'Emboar': 'emboar',
  'Oshawott': 'oshawott',
  'Dewott': 'dewott',
  'Samurott': 'samurott',
  'Patrat': 'patrat',
  'Watchog': 'watchog',
  'Lillipup': 'lillipup',
  'Herdier': 'herdier',
  'Stoutland': 'stoutland',
  'Purrloin': 'purrloin',
  'Liepard': 'liepard',
  'Pansage': 'pansage',
  'Simisage': 'simisage',
  'Pansear': 'pansear',
  'Simisear': 'simisear',
  'Panpour': 'panpour',
  'Simipour': 'simipour',
  'Munna': 'munna',
  'Musharna': 'musharna',
  'Pidove': 'pidove',
  'Tranquill': 'tranquill',
  'Unfezant': 'unfezant',
  'Blitzle': 'blitzle',
  'Zebstrika': 'zebstrika',
  'Roggenrola': 'roggenrola',
  'Boldore': 'boldore',
  'Gigalith': 'gigalith',
  'Woobat': 'woobat',
  'Swoobat': 'swoobat',
  'Drilbur': 'drilbur',
  'Excadrill': 'excadrill',
  'Audino': 'audino',
  'Mega Audino': 'audino-mega',
  'Timburr': 'timburr',
  'Gurdurr': 'gurdurr',
  'Conkeldurr': 'conkeldurr',
  'Tympole': 'tympole',
  'Palpitoad': 'palpitoad',
  'Seismitoad': 'seismitoad',
  'Throh': 'throh',
  'Sawk': 'sawk',
  'Sewaddle': 'sewaddle',
  'Swadloon': 'swadloon',
  'Leavanny': 'leavanny',
  'Venipede': 'venipede',
  'Whirlipede': 'whirlipede',
  'Scolipede': 'scolipede',
  'Cottonee': 'cottonee',
  'Whimsicott': 'whimsicott',
  'Petilil': 'petilil',
  'Lilligant': 'lilligant',
  'Basculin (Red-Striped Form)': 'basculin-red-striped',
  'Basculin (Blue-Striped Form)': 'basculin-blue-striped',
  'Sandile': 'sandile',
  'Krokorok': 'krokorok',
  'Krookodile': 'krookodile',
  'Darumaka': 'darumaka',
  'Darmanitan (Standard Mode)': 'darmanitan-standard',
  'Darmanitan (Zen Mode)': 'darmanitan-zen',
  'Maractus': 'maractus',
  'Dwebble': 'dwebble',
  'Crustle': 'crustle',
  'Scraggy': 'scraggy',
  'Scrafty': 'scrafty',
  'Sigilyph': 'sigilyph',
  'Yamask': 'yamask',
  'Cofagrigus': 'cofagrigus',
  'Tirtouga': 'tirtouga',
  'Carracosta': 'carracosta',
  'Archen': 'archen',
  'Archeops': 'archeops',
  'Trubbish': 'trubbish',
  'Garbodor': 'garbodor',
  'Zorua': 'zorua',
  'Zoroark': 'zoroark',
  'Minccino': 'minccino',
  'Cinccino': 'cinccino',
  'Gothita': 'gothita',
  'Gothorita': 'gothorita',
  'Gothitelle': 'gothitelle',
  'Solosis': 'solosis',
  'Duosion': 'duosion',
  'Reuniclus': 'reuniclus',
  'Ducklett': 'ducklett',
  'Swanna': 'swanna',
  'Vanillite': 'vanillite',
  'Vanillish': 'vanillish',
  'Vanilluxe': 'vanilluxe',
  'Deerling': 'deerling',
  'Sawsbuck': 'sawsbuck',
  'Emolga': 'emolga',
  'Karrablast': 'karrablast',
  'Escavalier': 'escavalier',
  'Foongus': 'foongus',
  'Amoonguss': 'amoonguss',
  'Frillish': 'frillish',
  'Jellicent': 'jellicent',
  'Alomomola': 'alomomola',
  'Joltik': 'joltik',
  'Galvantula': 'galvantula',
  'Ferroseed': 'ferroseed',
  'Ferrothorn': 'ferrothorn',
  'Klink': 'klink',
  'Klang': 'klang',
  'Klinklang': 'klinklang',
  'Tynamo': 'tynamo',
  'Eelektrik': 'eelektrik',
  'Eelektross': 'eelektross',
  'Elgyem': 'elgyem',
  'Beheeyem': 'beheeyem',
  'Litwick': 'litwick',
  'Lampent': 'lampent',
  'Chandelure': 'chandelure',
  'Axew': 'axew',
  'Fraxure': 'fraxure',
  'Haxorus': 'haxorus',
  'Cubchoo': 'cubchoo',
  'Beartic': 'beartic',
  'Cryogonal': 'cryogonal',
  'Shelmet': 'shelmet',
  'Accelgor': 'accelgor',
  'Stunfisk': 'stunfisk',
  'Mienfoo': 'mienfoo',
  'Mienshao': 'mienshao',
  'Druddigon': 'druddigon',
  'Golett': 'golett',
  'Golurk': 'golurk',
  'Pawniard': 'pawniard',
  'Bisharp': 'bisharp',
  'Bouffalant': 'bouffalant',
  'Rufflet': 'rufflet',
  'Braviary': 'braviary',
  'Vullaby': 'vullaby',
  'Mandibuzz': 'mandibuzz',
  'Heatmor': 'heatmor',
  'Durant': 'durant',
  'Deino': 'deino',
  'Zweilous': 'zweilous',
  'Hydreigon': 'hydreigon',
  'Larvesta': 'larvesta',
  'Volcarona': 'volcarona',
  'Cobalion': 'cobalion',
  'Terrakion': 'terrakion',
  'Virizion': 'virizion',
  'Tornadus (Incarnate Forme)': 'tornadus-incarnate',
  'Tornadus (Therian Forme)': 'tornadus-therian',
  'Thundurus (Incarnate Forme)': 'thundurus-incarnate',
  'Thundurus (Therian Forme)': 'thundurus-therian',
  'Reshiram': 'reshiram',
  'Zekrom': 'zekrom',
  'Landorus (Incarnate Forme)': 'landorus-incarnate',
  'Landorus (Therian Forme)': 'landorus-therian',
  'Kyurem': 'kyurem',
  'Kyurem (Black Kyurem)': 'kyurem-black',
  'Kyurem (White Kyurem)': 'kyurem-white',
  'Keldeo (Ordinary Forme)': 'keldeo-ordinary',
  'Keldeo (Resolute Forme)': 'keldeo-resolute',
  'Meloetta (Aria Forme)': 'meloetta-aria',
  'Meloetta (Pirouette Forme)': 'meloetta-pirouette',
  'Genesect': 'genesect',
  'Chespin': 'chespin',
  'Quilladin': 'quilladin',
  'Chesnaught': 'chesnaught',
  'Fennekin': 'fennekin',
  'Braixen': 'braixen',
  'Delphox': 'delphox',
  'Froakie': 'froakie',
  'Frogadier': 'frogadier',
  'Greninja': 'greninja',
  'Greninja (Ash-Greninja)': 'greninja-ash',
  'Bunnelby': 'bunnelby',
  'Diggersby': 'diggersby',
  'Fletchling': 'fletchling',
  'Fletchinder': 'fletchinder',
  'Talonflame': 'talonflame',
  'Scatterbug': 'scatterbug',
  'Spewpa': 'spewpa',
  'Vivillon': 'vivillon',
  'Litleo': 'litleo',
  'Pyroar': 'pyroar',
  'Flabébé': 'flabebe',
  'Floette': 'floette',
  'Florges': 'florges',
  'Skiddo': 'skiddo',
  'Gogoat': 'gogoat',
  'Pancham': 'pancham',
  'Pangoro': 'pangoro',
  'Furfrou': 'furfrou',
  'Espurr': 'espurr',
  'Meowstic (Male)': 'meowstic-male',
  'Meowstic (Female)': 'meowstic-female',
  'Honedge': 'honedge',
  'Doublade': 'doublade',
  'Aegislash (Blade Forme)': 'aegislash-blade',
  'Aegislash (Shield Forme)': 'aegislash-shield',
  'Spritzee': 'spritzee',
  'Aromatisse': 'aromatisse',
  'Swirlix': 'swirlix',
  'Slurpuff': 'slurpuff',
  'Inkay': 'inkay',
  'Malamar': 'malamar',
  'Binacle': 'binacle',
  'Barbaracle': 'barbaracle',
  'Skrelp': 'skrelp',
  'Dragalge': 'dragalge',
  'Clauncher': 'clauncher',
  'Clawitzer': 'clawitzer',
  'Helioptile': 'helioptile',
  'Heliolisk': 'heliolisk',
  'Tyrunt': 'tyrunt',
  'Tyrantrum': 'tyrantrum',
  'Amaura': 'amaura',
  'Aurorus': 'aurorus',
  'Sylveon': 'sylveon',
  'Hawlucha': 'hawlucha',
  'Dedenne': 'dedenne',
  'Carbink': 'carbink',
  'Goomy': 'goomy',
  'Sliggoo': 'sliggoo',
  'Goodra': 'goodra',
  'Klefki': 'klefki',
  'Phantump': 'phantump',
  'Trevenant': 'trevenant',
  'Pumpkaboo (Average Size)': 'pumpkaboo-average',
  'Pumpkaboo (Small Size)': 'pumpkaboo-small',
  'Pumpkaboo (Large Size)': 'pumpkaboo-large',
  'Pumpkaboo (Super Size)': 'pumpkaboo-super',
  'Gourgeist (Average Size)': 'gourgeist-average',
  'Gourgeist (Small Size)': 'gourgeist-small',
  'Gourgeist (Large Size)': 'gourgeist-large',
  'Gourgeist (Super Size)': 'gourgeist-super',
  'Bergmite': 'bergmite',
  'Avalugg': 'avalugg',
  'Noibat': 'noibat',
  'Noivern': 'noivern',
  'Xerneas': 'xerneas',
  'Yveltal': 'yveltal',
  'Zygarde (50% Forme)': 'zygarde-50',
  'Zygarde (10% Forme)': 'zygarde-10',
  'Zygarde (Complete Forme)': 'zygarde-complete',
  'Diancie': 'diancie',
  'Mega Diancie': 'diancie-mega',
  'Hoopa (Hoopa Confined)': 'hoopa-confined',
  'Hoopa (Hoopa Unbound)': 'hoopa-unbound',
  'Volcanion': 'volcanion',
  'Rowlet': 'rowlet',
  'Dartrix': 'dartrix',
  'Decidueye': 'decidueye',
  'Litten': 'litten',
  'Torracat': 'torracat',
  'Incineroar': 'incineroar',
  'Popplio': 'popplio',
  'Brionne': 'brionne',
  'Primarina': 'primarina',
  'Pikipek': 'pikipek',
  'Trumbeak': 'trumbeak',
  'Toucannon': 'toucannon',
  'Yungoos': 'yungoos',
  'Gumshoos': 'gumshoos',
  'Grubbin': 'grubbin',
  'Charjabug': 'charjabug',
  'Vikavolt': 'vikavolt',
  'Crabrawler': 'crabrawler',
  'Crabominable': 'crabominable',
  'Oricorio (Baile Style)': 'oricorio-baile',
  'Oricorio (Pom-Pom Style)': 'oricorio-pom-pom',
  'Oricorio (Pa\'u Style)': 'oricorio-pau',
  'Oricorio (Sensu Style)': 'oricorio-sensu',
  'Cutiefly': 'cutiefly',
  'Ribombee': 'ribombee',
  'Rockruff': 'rockruff',
  'Rockruff (Own Tempo Rockruff)': 'rockruff-own-tempo',
  'Lycanroc (Midday Form)': 'lycanroc-midday',
  'Lycanroc (Midnight Form)': 'lycanroc-midnight',
  'Lycanroc (Dusk Form)': 'lycanroc-dusk',
  'Wishiwashi (Solo Form)': 'wishiwashi-solo',
  'Wishiwashi (School Form)': 'wishiwashi-school',
  'Mareanie': 'mareanie',
  'Toxapex': 'toxapex',
  'Mudbray': 'mudbray',
  'Mudsdale': 'mudsdale',
  'Dewpider': 'dewpider',
  'Araquanid': 'araquanid',
  'Fomantis': 'fomantis',
  'Lurantis': 'lurantis',
  'Morelull': 'morelull',
  'Shiinotic': 'shiinotic',
  'Salandit': 'salandit',
  'Salazzle': 'salazzle',
  'Stufful': 'stufful',
  'Bewear': 'bewear',
  'Bounsweet': 'bounsweet',
  'Steenee': 'steenee',
  'Tsareena': 'tsareena',
  'Comfey': 'comfey',
  'Oranguru': 'oranguru',
  'Passimian': 'passimian',
  'Wimpod': 'wimpod',
  'Golisopod': 'golisopod',
  'Sandygast': 'sandygast',
  'Palossand': 'palossand',
  'Pyukumuku': 'pyukumuku',
  'Type: Null': 'type-null',
  'Silvally': 'silvally',
  'Minior (Meteor Form)': 'minior-meteor',
  'Minior (Core Form)': 'minior-core',
  'Komala': 'komala',
  'Turtonator': 'turtonator',
  'Togedemaru': 'togedemaru',
  'Mimikyu': 'mimikyu',
  'Bruxish': 'bruxish',
  'Drampa': 'drampa',
  'Dhelmise': 'dhelmise',
  'Jangmo-o': 'jangmo-o',
  'Hakamo-o': 'hakamo-o',
  'Kommo-o': 'kommo-o',
  'Tapu Koko': 'tapu-koko',
  'Tapu Lele': 'tapu-lele',
  'Tapu Bulu': 'tapu-bulu',
  'Tapu Fini': 'tapu-fini',
  'Cosmog': 'cosmog',
  'Cosmoem': 'cosmoem',
  'Solgaleo': 'solgaleo',
  'Lunala': 'lunala',
  'Nihilego': 'nihilego',
  'Buzzwole': 'buzzwole',
  'Pheromosa': 'pheromosa',
  'Xurkitree': 'xurkitree',
  'Celesteela': 'celesteela',
  'Kartana': 'kartana',
  'Guzzlord': 'guzzlord',
  'Necrozma': 'necrozma',
  'Necrozma (Dusk Mane Necrozma)': 'necrozma-dusk-mane',
  'Necrozma (Dawn Wings Necrozma)': 'necrozma-dawn-wings',
  'Necrozma (Ultra Necrozma)': 'necrozma-ultra',
  'Magearna': 'magearna',
  'Marshadow': 'marshadow',
  'Poipole': 'poipole',
  'Naganadel': 'naganadel',
  'Stakataka': 'stakataka',
  'Blacephalon': 'blacephalon',
  'Zeraora': 'zeraora',
  'Meltan': 'meltan',
  'Melmetal': 'melmetal'
}

export default pokemons;
